[api_keys]
CHART_IMG_API_KEY = "U9PpfPfwJD7tqcBgaJXJj16Lg47gZcAB2oBiIEn1"
GEMINI_API_KEY = "AIzaSyCNslLSywpb3HPEBZF-Qbjb7APf75wzefQ"
PERPLEXITY_API_KEY = "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"
